repos:
# Check YAML; Fix end of files; Fix trailing whitespace
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-yaml
    name: Check Yaml
  - id: end-of-file-fixer
    name: Fix End of Files
  - id: trailing-whitespace
    name: Fix Trailing Whitespace
- repo: local
  hooks:
  - id: cargo-fmt
    name: Rust Formatter
    description: "A tool for formatting Rust code according to style guidelines."
    language: rust
    entry: rustfmt
    types: [rust]
