repos:
# Check YAML; Fix end of files; Fix trailing whitespace
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-yaml
    name: Check Yaml
  - id: end-of-file-fixer
    name: Fix End of Files
  - id: trailing-whitespace
    name: Fix Trailing Whitespace
# Formatter (cargo fmt), Validator, Linter
- repo: https://github.com/AceofSpades5757/rustfmt
  rev: 10eae9c6dbd41513951d71f70ff1ab864e86a75c
  hooks:
    - id: rustfmt
      name: Rust Formatter
      description: Formats Rust source code.
