# Requires `go install github.com/go-task/task/v3/cmd/task@latest`
version: "3"

tasks:
  default:
    - task help
  help:
    cmds:
      - task --list-all
  test:
    desc: Run tests.
    cmds:
      - cargo test --all-features
  book:
    # Requires `cargo install mdbook`
    desc: Serve book.
    cmds:
      - mdbook serve --open
