# Requires `go install github.com/go-task/task/v3/cmd/task@latest`
version: "3"

vars:
  BOOK_DIR: "./book"

tasks:
  default:
    silent: true
    cmd: task help
  help:
    silent: true
    cmds:
      - task --list
  test:
    desc: Run tests.
    cmds:
      - cargo test --all-features
  book:
    # Requires `cargo install mdbook`
    desc: Serve book.
    dir: "{{.BOOK_DIR}}"
    cmds:
      - mdbook serve --open
  book-build:
    # Requires `cargo install mdbook`
    desc: Build book for publication.
    dir: "{{.BOOK_DIR}}"
    cmds:
      - mdbook build
  clean:
    desc: Clean temp, cache, book, etc. files and directories.
    cmds:
      # Cargo Artifacts
      - cargo clean
      # mdbook Artifacts
      - rm -f "./index.html"
      - rm -f "{{.BOOK_DIR}}/index.html"
      - rm -rf "{{.BOOK_DIR}}/book/"
